In [ ]:
from pandas import read_html

In [ ]:
URL = "https://www.w3schools.com/python/python_ref_string.asp"
readHTML = read_html(URL)  # Put The URL To Get The Table

In [ ]:
readHTML # read_html return a list not a DataFrame

[            Method                                        Description
 0     capitalize()         Converts the first character to upper case
 1       casefold()                    Converts string into lower case
 2         center()                          Returns a centered string
 3          count()  Returns the number of times a specified value ...
 4         encode()           Returns an encoded version of the string
 5       endswith()  Returns true if the string ends with the speci...
 6     expandtabs()                    Sets the tab size of the string
 7           find()  Searches the string for a specified value and ...
 8         format()               Formats specified values in a string
 9     format_map()               Formats specified values in a string
 10         index()  Searches the string for a specified value and ...
 11       isalnum()  Returns True if all characters in the string a...
 12       isalpha()  Returns True if all characters in the string a...
 13       isascii()  Returns True if all characters in the string a...
 14     isdecimal()  Returns True if all characters in the string a...
 15       isdigit()  Returns True if all characters in the string a...
 16  isidentifier()        Returns True if the string is an identifier
 17       islower()  Returns True if all characters in the string a...
 18     isnumeric()  Returns True if all characters in the string a...
 19   isprintable()  Returns True if all characters in the string a...
 20       isspace()  Returns True if all characters in the string a...
 21       istitle()  Returns True if the string follows the rules o...
 22       isupper()  Returns True if all characters in the string a...
 23          join()  Converts the elements of an iterable into a st...
 24         ljust()     Returns a left justified version of the string
 25         lower()                  Converts a string into lower case
 26        lstrip()          Returns a left trim version of the string
 27     maketrans()  Returns a translation table to be used in tran...
 28     partition()  Returns a tuple where the string is parted int...
 29       replace()  Returns a string where a specified value is re...
 30         rfind()  Searches the string for a specified value and ...
 31        rindex()  Searches the string for a specified value and ...
 32         rjust()    Returns a right justified version of the string
 33    rpartition()  Returns a tuple where the string is parted int...
 34        rsplit()  Splits the string at the specified separator, ...
 35        rstrip()         Returns a right trim version of the string
 36         split()  Splits the string at the specified separator, ...
 37    splitlines()  Splits the string at line breaks and returns a...
 38    startswith()  Returns true if the string starts with the spe...
 39         strip()            Returns a trimmed version of the string
 40      swapcase()  Swaps cases, lower case becomes upper case and...
 41         title()  Converts the first character of each word to u...
 42     translate()                        Returns a translated string
 43         upper()                  Converts a string into upper case
 44         zfill()  Fills the string with a specified number of 0 ...]

In [ ]:
# So To See The Table That Stored In List -->> Use Indexes
readHTML[0]

            Method                                        Description
0     capitalize()         Converts the first character to upper case
1       casefold()                    Converts string into lower case
2         center()                          Returns a centered string
3          count()  Returns the number of times a specified value ...
4         encode()           Returns an encoded version of the string
5       endswith()  Returns true if the string ends with the speci...
6     expandtabs()                    Sets the tab size of the string
7           find()  Searches the string for a specified value and ...
8         format()               Formats specified values in a string
9     format_map()               Formats specified values in a string
10         index()  Searches the string for a specified value and ...
11       isalnum()  Returns True if all characters in the string a...
12       isalpha()  Returns True if all characters in the string a...
13       isascii()  Returns True if all characters in the string a...
14     isdecimal()  Returns True if all characters in the string a...
15       isdigit()  Returns True if all characters in the string a...
16  isidentifier()        Returns True if the string is an identifier
17       islower()  Returns True if all characters in the string a...
18     isnumeric()  Returns True if all characters in the string a...
19   isprintable()  Returns True if all characters in the string a...
20       isspace()  Returns True if all characters in the string a...
21       istitle()  Returns True if the string follows the rules o...
22       isupper()  Returns True if all characters in the string a...
23          join()  Converts the elements of an iterable into a st...
24         ljust()     Returns a left justified version of the string
25         lower()                  Converts a string into lower case
26        lstrip()          Returns a left trim version of the string
27     maketrans()  Returns a translation table to be used in tran...
28     partition()  Returns a tuple where the string is parted int...
29       replace()  Returns a string where a specified value is re...
30         rfind()  Searches the string for a specified value and ...
31        rindex()  Searches the string for a specified value and ...
32         rjust()    Returns a right justified version of the string
33    rpartition()  Returns a tuple where the string is parted int...
34        rsplit()  Splits the string at the specified separator, ...
35        rstrip()         Returns a right trim version of the string
36         split()  Splits the string at the specified separator, ...
37    splitlines()  Splits the string at line breaks and returns a...
38    startswith()  Returns true if the string starts with the spe...
39         strip()            Returns a trimmed version of the string
40      swapcase()  Swaps cases, lower case becomes upper case and...
41         title()  Converts the first character of each word to u...
42     translate()                        Returns a translated string
43         upper()                  Converts a string into upper case
44         zfill()  Fills the string with a specified number of 0 ...

In [ ]:
# As You Can See In The Above DataFrame We Got All Methods Of String From W3Schools